1) Combined Categorical and Gaussian NB with sklearn (using train-test-split )
2) 1. using k-fold (using average of accuracies approach) (without shuffle)
3) 1. using k-fold (using append predictions to series approach) (with & without shuffle) 
4) 1. using stratified k-fold (using append predictions to series approach) (with shuffle)

In [1]:
# after removing data row as index row and changing column names
import pandas as pd
import numpy as np
df=pd.read_csv('C:\\Users\\soham\\Downloads\\adult.data',names=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','income'],header=None)
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [2]:
#replacing "?" by np.nan
df=df.replace(' ?',np.nan)
#replace missing values by mean,mode
for i in df.columns:
    if (type(df[i].dropna().tolist()[0])==str): #we are checking type of first value of each column after dropping NA's from it.
        df[i]=df[i].fillna(df[i].mode()[0])   #So, no problem even if first value of column turns out to be missing
    elif (type(df[i].dropna().tolist()[0])==float):  #we are checking type of first available element of that column using dropna 
        df[i]=df[i].fillna(df[i].mean())
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,United-States,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,Private,180211,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,Private,33811,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,Private,287372,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,Private,202822,HS-grad,9,Separated,Prof-specialty,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,Private,129912,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
#creating a dataframe with only integer/numerical type columns
dfint=pd.DataFrame()
for i in df.columns:
    if (type(df[i].tolist()[0])==int):
        dfint[i]=df[i].tolist()
dfint

       age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week
0       39   77516             13          2174             0              40
1       50   83311             13             0             0              13
2       38  215646              9             0             0              40
3       53  234721              7             0             0              40
4       28  338409             13             0             0              40
5       37  284582             14             0             0              40
6       49  160187              5             0             0              16
7       52  209642              9             0             0              45
8       31   45781             14         14084             0              50
9       42  159449             13          5178             0              40
10      37  280464             10             0             0              80
11      30  141297             13             0             0              40
12      23  122272             13             0             0              30
13      32  205019             12             0             0              50
14      40  121772             11             0             0              40
15      34  245487              4             0             0              45
16      25  176756              9             0             0              35
17      32  186824              9             0             0              40
18      38   28887              7             0             0              50
19      43  292175             14             0             0              45
20      40  193524             16             0             0              60
21      54  302146              9             0             0              20
22      35   76845              5             0             0              40
23      43  117037              7             0          2042              40
24      59  109015              9             0             0              40
25      56  216851             13             0             0              40
26      19  168294              9             0             0              40
27      54  180211             10             0             0              60
28      39  367260              9             0             0              80
29      49  193366              9             0             0              40
...    ...     ...            ...           ...           ...             ...
32531   30   33811             13             0             0              99
32532   34  204461             16             0             0              60
32533   54  337992             13             0             0              50
32534   37  179137             10             0             0              39
32535   22  325033              8             0             0              35
32536   34  160216             13             0             0              55
32537   30  345898              9             0             0              46
32538   38  139180             13         15020             0              45
32539   71  287372             16             0             0              10
32540   45  252208              9             0             0              40
32541   41  202822              9             0             0              32
32542   72  129912              9             0             0              25
32543   45  119199             12             0             0              48
32544   31  199655             14             0             0              30
32545   39  111499             12             0             0              20
32546   37  198216             12             0             0              40
32547   43  260761              9             0             0              40
32548   65   99359             15          1086             0              60
32549   43  255835             10             0             0              40
32550   43   27242             10             0             0              50
32551   32   34066              6             0             0              40
32552   43   84661             11             0             0              45
32553   32  116138             14             0             0              11
32554   53  321865             14             0             0              40
32555   22  310152             10             0             0              40
32556   27  257302             12             0             0              38
32557   40  154374              9             0             0              40
32558   58  151910              9             0             0              40
32559   22  201490              9             0             0              20
32560   52  287927              9         15024             0              40

[32561 rows x 6 columns]

In [4]:
#creating a dataframe with only integer/numerical type columns
dfobj=pd.DataFrame()
for i in df.columns:
    if (type(df[i].tolist()[0])==str):
        dfobj[i]=df[i].tolist()
dfobj

,workclass,education,marital-status,occupation,relationship,race,sex,native-country,income
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States,<=50K
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,<=50K
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,<=50K
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,<=50K
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,<=50K
5,Private,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States,<=50K
6,Private,9th,Married-spouse-absent,Other-service,Not-in-family,Black,Female,Jamaica,<=50K
7,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,>50K
8,Private,Masters,Never-married,Prof-specialty,Not-in-family,White,Female,United-States,>50K
9,Private,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,>50K
10,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,United-States,>50K
11,State-gov,Bachelors,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,India,>50K
12,Private,Bachelors,Never-married,Adm-clerical,Own-child,White,Female,United-States,<=50K
13,Private,Assoc-acdm,Never-married,Sales,Not-in-family,Black,Male,United-States,<=50K
14,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,United-States,>50K
15,Private,7th-8th,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,Mexico,<=50K
16,Self-emp-not-inc,HS-grad,Never-married,Farming-fishing,Own-child,White,Male,United-States,<=50K
17,Private,HS-grad,Never-married,Machine-op-inspct,Unmarried,White,Male,United-States,<=50K
18,Private,11th,Married-civ-spouse,Sales,Husband,White,Male,United-States,<=50K
19,Self-emp-not-inc,Masters,Divorced,Exec-managerial,Unmarried,White,Female,United-States,>50K
20,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,>50K
21,Private,HS-grad,Separated,Other-service,Unmarried,Black,Female,United-States,<=50K
22,Federal-gov,9th,Married-civ-spouse,Farming-fishing,Husband,Black,Male,United-States,<=50K
23,Private,11th,Married-civ-spouse,Transport-moving,Husband,White,Male,United-States,<=50K
24,Private,HS-grad,Divorced,Tech-support,Unmarried,White,Female,United-States,<=50K
25,Local-gov,Bachelors,Married-civ-spouse,Tech-support,Husband,White,Male,United-States,>50K
26,Private,HS-grad,Never-married,Craft-repair,Own-child,White,Male,United-States,<=50K
27,Private,Some-college,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,South,>50K
28,Private,HS-grad,Divorced,Exec-managerial,Not-in-family,White,Male,United-States,<=50K
29,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States,<=50K
...,...,...,...,...,...,...,...,...,...
32531,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Female,United-States,<=50K
32532,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,>50K
32533,Private,Bachelors,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,Japan,>50K
32534,Private,Some-college,Divorced,Adm-clerical,Unmarried,White,Female,United-States,<=50K
32535,Private,12th,Never-married,Protective-serv,Own-child,Black,Male,United-States,<=50K
32536,Private,Bachelors,Never-married,Exec-managerial,Not-in-family,White,Female,United-States,>50K
32537,Private,HS-grad,Never-married,Craft-repair,Not-in-family,Black,Male,United-States,<=50K
32538,Private,Bachelors,Divorced,Prof-specialty,Unmarried,Black,Female,United-States,>50K
32539,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,>50K
32540,State-gov,HS-grad,Separated,Adm-clerical,Own-child,White,Female,United-States,<=50K
32541,Private,HS-grad,Separated,Prof-specialty,Not-in-family,Black,Female,United-States,<=50K
32542,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
32543,Local-gov,Assoc-acdm,Divorced,Prof-specialty,Unmarried,White,Female,United-States,<=50K
32544,Private,Masters,Divorced,Other-service,Not-in-family,Other,Female,United-States,<=50K
32545,Local-gov,Assoc-acdm,Married-civ-spouse,Adm-clerical,Wife,White,Female,United-States,>50K
32546,Private,Assoc-acdm,Divorced,Tech-support,Not-in-family,White,Female,United-States,<=50K
32547,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,Mexico,<=50K
32548,Self-emp-not-inc,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Male,United-States,<=50K
32549,State-gov,Some-college,Divorced,Adm-clerical,Other-relative,White,Female,United-States,<=50K
32550,Self-emp-not-inc,Some-college,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States,<=50K
32551,Private,10th,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,United-States,<=50K
32552,Private,Assoc-voc,Married-civ-spouse,Sales,Husband,White,Male,United-States,<=50K
32553,Private,Masters,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,Taiwan,<=50K
32554,Private,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,>50K
32555,Private,Some-college,Never-married,Protective-serv,Not-in-family,White,Male,United-States,<=50K
32556,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States,<=50K
32557,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States,>50K
32558,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States,<=50K
32559,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States,<=50K
32560,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States,>50K

In [5]:
#performing train-test-split on our dataframe
import numpy as np
from sklearn.model_selection import train_test_split

# X consists of only categorical columns, y consists of output column("income")
X, y = dfobj.iloc[:,0:7],dfobj.iloc[:,[-1]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

# X1 consists of only integer type columns, y1 consists of output column("income")
X1, y1 = dfint.iloc[:,:],df.iloc[:,[-1]]
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3, random_state=5)

# X2 consists of all input columns, y2 consists of output column("income")
X2, y2 = df.iloc[:,0:13],df.iloc[:,[-1]]
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3, random_state=5)

In [6]:
import numpy as np
X1 = np.array(X1_train.values)
Y1 = np.array(y1_train.values)
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X1, Y1)

#conditional probability outcome for [<=50K,>50K] of each row of test data
proba_list=clf.predict_proba(np.array(X1_test.values))
proba_list

C:\Users\soham\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[2.56505131e-05, 9.99974349e-01],
       [9.93273305e-01, 6.72669466e-03],
       [9.97178966e-01, 2.82103394e-03],
       ...,
       [1.53188750e-05, 9.99984681e-01],
       [9.86016045e-01, 1.39839549e-02],
       [9.84364590e-01, 1.56354101e-02]])

In [7]:
proba_list[0]

array([2.56505131e-05, 9.99974349e-01])

In [8]:
clf.predict_proba([np.array(X1_test.values)[0]])[0]

array([2.56505131e-05, 9.99974349e-01])

In [10]:
#to obtain a dictionary of the class priors of output column
def getClassPriors(opcol):
    opcol=list(opcol)
    CP={i:opcol.count(i)/len(opcol) for i in np.unique(opcol)}
    return(CP)

getClassPriors(y_train['income'])

{' <=50K': 0.7587311337311338, ' >50K': 0.24126886626886626}

In [11]:
# calculating the conditional probability of each category for each output value
def getcondProbs_obj(inp_traindf,op_traindf,opcol):
    Conpro={j:{k:(  len(inp_traindf[i][(inp_traindf[i]==j) & (op_traindf[opcol]==k)])  /  len(inp_traindf[i])  )   /   (  len(op_traindf[opcol][(op_traindf[opcol]==k)])  /  len(op_traindf[opcol])  )  for k in np.unique(op_traindf[opcol]) }  for i in inp_traindf.columns.values  for j in np.unique(inp_traindf[i]) }               
    return Conpro 

getcondProbs_obj(X_train,y_train,'income')

{' State-gov': {' <=50K': 0.03851269299716648, ' >50K': 0.0452809601745772},
 ' Federal-gov': {' <=50K': 0.023940322673914303,
  ' >50K': 0.05091834879068922},
 ' Local-gov': {' <=50K': 0.06025559474932053, ' >50K': 0.0734679032551373},
 ' Self-emp-not-inc': {' <=50K': 0.07459665760712426,
  ' >50K': 0.09092562284051646},
 ' Private': {' <=50K': 0.7815879257503036, ' >50K': 0.662302236770322},
 ' Without-pay': {' <=50K': 0.000693922396345342, ' >50K': 0.0},
 ' Never-worked': {' <=50K': 0.000346961198172671, ' >50K': 0.0},
 ' Self-emp-inc': {' <=50K': 0.020065922627652805,
  ' >50K': 0.07710492816875796},
 ' 11th': {' <=50K': 0.045104955762447226, ' >50K': 0.008001454809965449},
 ' HS-grad': {' <=50K': 0.35968310877233567, ' >50K': 0.21294780869248955},
 ' Preschool': {' <=50K': 0.0019661134563118024, ' >50K': 0.0},
 ' Assoc-acdm': {' <=50K': 0.0327300063609553, ' >50K': 0.03364248045099109},
 ' Some-college': {' <=50K': 0.23940322673914297, ' >50K': 0.1789416257501364},
 ' Assoc-voc': {' <=50K': 0.0405366333198404, ' >50K': 0.04582651391162029},
 ' 5th-6th': {' <=50K': 0.01254843000057827, ' >50K': 0.0014548099654482633},
 ' 12th': {' <=50K': 0.01549760018504597, ' >50K': 0.0036370249136206587},
 ' Masters': {' <=50K': 0.03116868096917828, ' >50K': 0.12293144208037826},
 ' Doctorate': {' <=50K': 0.004915283640779506, ' >50K': 0.04018912529550828},
 ' 1st-4th': {' <=50K': 0.006823570230729196, ' >50K': 0.0007274049827241316},
 ' 10th': {' <=50K': 0.03388654368819753, ' >50K': 0.0074559010729223505},
 ' Bachelors': {' <=50K': 0.1269877985311976, ' >50K': 0.28186943080560106},
 ' 9th': {' <=50K': 0.0195454808303938, ' >50K': 0.004000727404982724},
 ' 7th-8th': {' <=50K': 0.023188573411206847, ' >50K': 0.005455537370430988},
 ' Prof-school': {' <=50K': 0.00601399410165963, ' >50K': 0.05291871249318058},
 ' Married-AF-spouse': {' <=50K': 0.00040478806453478285,
  ' >50K': 0.0007274049827241316},
 ' Divorced': {' <=50K': 0.15925518996125598, ' >50K': 0.05528277868703401},
 ' Widowed': {' <=50K': 0.03781877060082114, ' >50K': 0.009819967266775777},
 ' Separated': {' <=50K': 0.03816573179899381, ' >50K': 0.008183306055646482},
 ' Never-married': {' <=50K': 0.41404036315272075,
  ' >50K': 0.06310238225131842},
 ' Married-spouse-absent': {' <=50K': 0.014919331521424852,
  ' >50K': 0.004182578650663757},
 ' Married-civ-spouse': {' <=50K': 0.33539582490024866,
  ' >50K': 0.8587015821058375},
 ' Transport-moving': {' <=50K': 0.05042502746776152,
  ' >50K': 0.03927986906710311},
 ' Other-service': {' <=50K': 0.12669866419938702,
  ' >50K': 0.01873067830514639},
 ' Handlers-cleaners': {' <=50K': 0.05198635285953854,
  ' >50K': 0.01054737224949991},
 ' Farming-fishing': {' <=50K': 0.03498525414907766,
  ' >50K': 0.014184397163120569},
 ' Protective-serv': {' <=50K': 0.017752847973168333,
  ' >50K': 0.024186215675577376},
 ' Adm-clerical': {' <=50K': 0.13381136876192679, ' >50K': 0.0680123658847063},
 ' Armed-Forces': {' <=50K': 0.000346961198172671,
  ' >50K': 0.0001818512456810329},
 ' Prof-specialty': {' <=50K': 0.1582721332331001,
  ' >50K': 0.25895617384979086},
 ' Priv-house-serv': {' <=50K': 0.005898340368935407,
  ' >50K': 0.0001818512456810329},
 ' Sales': {' <=50K': 0.11016018041982303, ' >50K': 0.1276595744680851},
 ' Exec-managerial': {' <=50K': 0.08425374428959694,
  ' >50K': 0.2509547190398254},
 ' Craft-repair': {' <=50K': 0.1284334701902504, ' >50K': 0.12165848336061101},
 ' Tech-support': {' <=50K': 0.026889492858382002,
  ' >50K': 0.03346062920531006},
 ' Machine-op-inspct': {' <=50K': 0.07008616203087954,
  ' >50K': 0.032005819239861795},
 ' Husband': {' <=50K': 0.29381830798589026, ' >50K': 0.7561374795417348},
 ' Own-child': {' <=50K': 0.20482276065460012, ' >50K': 0.0074559010729223505},
 ' Not-in-family': {' <=50K': 0.2982131498294107,
  ' >50K': 0.10911074740861976},
 ' Wife': {' <=50K': 0.033481755623662755, ' >50K': 0.09783597017639571},
 ' Other-relative': {' <=50K': 0.039900537789857166,
  ' >50K': 0.004909983633387889},
 ' Unmarried': {' <=50K': 0.12976348811657895, ' >50K': 0.024549918166939442},
 ' Black': {' <=50K': 0.11201064014341061, ' >50K': 0.05055464629932715},
 ' Asian-Pac-Islander': {' <=50K': 0.030937373503729833,
  ' >50K': 0.03436988543371522},
 ' White': {' <=50K': 0.8360608338634129, ' >50K': 0.9083469721767594},
 ' Amer-Indian-Eskimo': {' <=50K': 0.010697970276990688,
  ' >50K': 0.004000727404982724},
 ' Other': {' <=50K': 0.010293182212455907, ' >50K': 0.002727768685215494},
 ' Male': {' <=50K': 0.6120973804429538, ' >50K': 0.8486997635933806},
 ' Female': {' <=50K': 0.38790261955704625, ' >50K': 0.15130023640661938}}

In [12]:
# predicting the output of a single row 
# for each possible output value, (multiplying together the condprob of each element of input row)
# and then declaring the greater value of multiplication as our predection

def predictone(x_obj,x_int,condprobs,classpriors):
    outprob={}
    for i in classpriors.keys():
        l=[condprobs[x_obj[j]][i] for j in x_obj.index]
        outprob[i]=np.prod(l)*classpriors[i]
    #print(outprob)  
    
    #creating a dictionary of gaussian nb predict_proba values
    k=clf.classes_
    v=clf.predict_proba([x_int])[0] 
    #remember, in clf.predict_proba([x_int]) prediction probabilities for outputs are ordered as their are output values in clf. classes_ 
    predvals=dict(zip(k,v))
    #print(predvals)
    
    #creating combined dictionary
    comb={k:predvals[k]*outprob[k] for k in clf.classes_ }
    #print(comb)
    
    return (max(comb, key=comb.get))

#clf.predict_proba([np.array(X1_test.values)[0]])[0]
predictone(X_test.iloc[0,0:7],X1_test.iloc[0,0:6],  getcondProbs_obj(X_train,y_train,'income'),  getClassPriors(y_train['income']))

' >50K'

In [13]:
3.821379298631455e-07*0.012190344941869383

4.658393180403633e-09

In [14]:
getClassPriors(y_train['income']).keys()

dict_keys([' <=50K', ' >50K'])

In [15]:
clf.classes_

array([' <=50K', ' >50K'], dtype='<U6')

In [16]:
def predictall(X_test,X1_test,X2_test,condprobs,classpriors):
    y_pred=X2_test.apply(lambda row:predictone(row[X_test.columns],row[X1_test.columns],condprobs,classpriors), axis=1 )
    return y_pred

predictall(X_test, X1_test, X2_test,  getcondProbs_obj(X_train,y_train,'income'),  getClassPriors(y_train['income']))

32264      >50K
28024     <=50K
9347      <=50K
10427     <=50K
4810       >50K
11139     <=50K
20926     <=50K
24150     <=50K
15504     <=50K
9407       >50K
8963       >50K
12107     <=50K
157        >50K
21946     <=50K
14238      >50K
2684      <=50K
24774     <=50K
31521     <=50K
20148      >50K
1783      <=50K
25516     <=50K
15029     <=50K
13136     <=50K
25779     <=50K
26879     <=50K
10207     <=50K
11367     <=50K
23913     <=50K
30387     <=50K
9346      <=50K
          ...
25053     <=50K
26478     <=50K
23368     <=50K
26636     <=50K
22505     <=50K
6995      <=50K
59         >50K
11276     <=50K
27296     <=50K
1431      <=50K
13144     <=50K
23339     <=50K
3490      <=50K
8074      <=50K
20341     <=50K
24870     <=50K
14760     <=50K
17919     <=50K
30833     <=50K
4343       >50K
5220      <=50K
12702     <=50K
18032     <=50K
25331     <=50K
17952     <=50K
7577      <=50K
17553     <=50K
24131      >50K
13961     <=50K
3335      <=50K
Length: 9769, dtype: object

In [17]:
type(predictall(X_test, X1_test, X2_test,  getcondProbs_obj(X_train,y_train,'income'),  getClassPriors(y_train['income'])) )

pandas.core.series.Series

In [18]:
def accuracy(actlist,predlist):
    acc=(sum([a==b for (a,b) in zip(predlist,actlist)])/len(predlist))*100
    print('Accuracy of Algorithm is : ',acc,'%')
    return acc
    
accuracy(y_test['income'].tolist(), predictall(X_test, X1_test, X2_test,  getcondProbs_obj(X_train,y_train,'income'),  getClassPriors(y_train['income'])))

Accuracy of Algorithm is :  81.2979834169311 %

81.2979834169311

Using K-fold cross validation (without shuffle)

(Using average of accuracies approach)

In [19]:
import numpy as np
from sklearn.model_selection import KFold

#categorical data
X = dfobj.iloc[:,0:7]
y = dfobj.iloc[:,[-1]]

# X1 consists of only integer type columns, y1 consists of output column("income")
X1, y1 = dfint.iloc[:,:],df.iloc[:,[-1]]
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3, random_state=5)

# X2 consists of all input columns, y2 consists of output column("income")
X2, y2 = df.iloc[:,0:13],df.iloc[:,[-1]]
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3, random_state=5)

kf = KFold(n_splits=5)
#kf = KFold(n_splits=5, shuffle=True, random_state=5)
# by default shuffle is false, but we can use (shuffle=True) with a random state to split data after shuffling

kf.get_n_splits(X)

print(kf)

KFold(n_splits=5, random_state=None, shuffle=False)

In [20]:
acc=[]
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    X1_train, X1_test = X1.iloc[train_index], X1.iloc[test_index]
    y1_train, y1_test = y1.iloc[train_index], y1.iloc[test_index]
    
    X2_train, X2_test = X2.iloc[train_index], X2.iloc[test_index]
    y2_train, y2_test = y2.iloc[train_index], y2.iloc[test_index]
    
    acc.append(accuracy(y_test['income'].tolist(), predictall(X_test, X1_test, X2_test,  getcondProbs_obj(X_train,y_train,'income'),  getClassPriors(y_train['income']))))
    
print(acc)

#taking average of accuracies of all the folds
accavg=sum(acc)/len(acc)
accavg

TRAIN: [ 6513  6514  6515 ... 32558 32559 32560] TEST: [   0    1    2 ... 6510 6511 6512]
Accuracy of Algorithm is :  81.16075541225241 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [ 6513  6514  6515 ... 13022 13023 13024]
Accuracy of Algorithm is :  81.38820638820638 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [13025 13026 13027 ... 19534 19535 19536]
Accuracy of Algorithm is :  81.83353808353809 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [19537 19538 19539 ... 26046 26047 26048]
Accuracy of Algorithm is :  80.8046683046683 %
TRAIN: [    0     1     2 ... 26046 26047 26048] TEST: [26049 26050 26051 ... 32558 32559 32560]
Accuracy of Algorithm is :  81.71068796068795 %
[81.16075541225241, 81.38820638820638, 81.83353808353809, 80.8046683046683, 81.71068796068795]

81.37957122987062

Using append predictions to series approach (without shuffle)

This involves comparing all the predicted outputs at once with actual outputs instead of (comparing fold by fold and then taking average of accuracies). So, accuracy will be found out only once by appending predictions of all the folds together in a series and comparing it with the series of actual output values.

In [21]:
pred_series=pd.Series()
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    X1_train, X1_test = X1.iloc[train_index], X1.iloc[test_index]
    y1_train, y1_test = y1.iloc[train_index], y1.iloc[test_index]
    
    X2_train, X2_test = X2.iloc[train_index], X2.iloc[test_index]
    y2_train, y2_test = y2.iloc[train_index], y2.iloc[test_index]
    
    pred_series=pred_series.append(predictall(X_test, X1_test, X2_test,  getcondProbs_obj(X_train,y_train,'income'),  getClassPriors(y_train['income'])))
    #we need to append and store the updated series in original pred_series, otherwise printing it would return an empty series

print(pred_series)

accuracy=(sum([a==b for (a,b) in zip(pred_series,df['income'])])/len(pred_series))*100
print('The final accuracy after appending all the predicted values in a series is : ',accuracy,'%')

TRAIN: [ 6513  6514  6515 ... 32558 32559 32560] TEST: [   0    1    2 ... 6510 6511 6512]
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [ 6513  6514  6515 ... 13022 13023 13024]
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [13025 13026 13027 ... 19534 19535 19536]
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [19537 19538 19539 ... 26046 26047 26048]
TRAIN: [    0     1     2 ... 26046 26047 26048] TEST: [26049 26050 26051 ... 32558 32559 32560]
0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
5         <=50K
6         <=50K
7         <=50K
8          >50K
9          >50K
10        <=50K
11        <=50K
12        <=50K
13        <=50K
14        <=50K
15        <=50K
16        <=50K
17        <=50K
18        <=50K
19        <=50K
20         >50K
21        <=50K
22        <=50K
23         >50K
24        <=50K
25        <=50K
26        <=50K
27        <=50K
28        <=50K
29        <=50K
          ...
32531     <=50K
32532      >50K
32533     <=50K
32534     <=50K
32535     <=50K
32536     <=50K
32537     <=50K
32538      >50K
32539     <=50K
32540     <=50K
32541     <=50K
32542     <=50K
32543     <=50K
32544     <=50K
32545     <=50K
32546     <=50K
32547     <=50K
32548     <=50K
32549     <=50K
32550     <=50K
32551     <=50K
32552     <=50K
32553     <=50K
32554     <=50K
32555     <=50K
32556     <=50K
32557     <=50K
32558     <=50K
32559     <=50K
32560      >50K
Length: 32561, dtype: object
The final accuracy after appending all the predicted values in a series is :  81.3795645096895 %

Using K-fold (with shuffle) (Using append predictions to series approach)

In [22]:
import numpy as np
from sklearn.model_selection import KFold

#categorical data
X = dfobj.iloc[:,0:7]
y = dfobj.iloc[:,[-1]]

#kf = KFold(n_splits=5)
kf = KFold(n_splits=5, shuffle=True, random_state=5)
# by default shuffle is false, but we can use (shuffle=True) with a random state to split data after shuffling

kf.get_n_splits(X)

print(kf)

KFold(n_splits=5, random_state=5, shuffle=True)

In [23]:
pred_series=pd.Series()
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    X1_train, X1_test = X1.iloc[train_index], X1.iloc[test_index]
    y1_train, y1_test = y1.iloc[train_index], y1.iloc[test_index]
    
    X2_train, X2_test = X2.iloc[train_index], X2.iloc[test_index]
    y2_train, y2_test = y2.iloc[train_index], y2.iloc[test_index]
    
    pred_series=pred_series.append(predictall(X_test, X1_test, X2_test,  getcondProbs_obj(X_train,y_train,'income'),  getClassPriors(y_train['income'])))
    #we need to append and store the updated series in original pred_series, otherwise printing it would return an empty series
    

print(pred_series)

accuracy=(sum([a==b for (a,b) in zip(pred_series,df.iloc[pred_series.index,-1])])/len(pred_series))*100
print('The final accuracy after appending all the predicted values in a series is : ',accuracy,'%')

TRAIN: [    0     1     2 ... 32557 32559 32560] TEST: [    5     6    17 ... 32541 32550 32558]
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [    7    12    14 ... 32545 32551 32553]
TRAIN: [    1     2     3 ... 32557 32558 32560] TEST: [    0     8     9 ... 32546 32549 32559]
TRAIN: [    0     3     5 ... 32557 32558 32559] TEST: [    1     2     4 ... 32554 32556 32560]
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [    3    10    18 ... 32548 32555 32557]
5         <=50K
6         <=50K
17        <=50K
19        <=50K
21        <=50K
27        <=50K
28        <=50K
29        <=50K
33        <=50K
38        <=50K
39        <=50K
57        <=50K
58        <=50K
61        <=50K
62        <=50K
64        <=50K
70        <=50K
82        <=50K
83        <=50K
86        <=50K
92        <=50K
93         >50K
94        <=50K
95        <=50K
101        >50K
103       <=50K
111       <=50K
119       <=50K
121       <=50K
124       <=50K
          ...
32399      >50K
32406     <=50K
32420     <=50K
32422     <=50K
32426     <=50K
32433     <=50K
32439     <=50K
32442     <=50K
32446     <=50K
32447     <=50K
32449      >50K
32454     <=50K
32459     <=50K
32461     <=50K
32463     <=50K
32469     <=50K
32470     <=50K
32473     <=50K
32475     <=50K
32490     <=50K
32494     <=50K
32506     <=50K
32508     <=50K
32514     <=50K
32526     <=50K
32534     <=50K
32535     <=50K
32548     <=50K
32555     <=50K
32557     <=50K
Length: 32561, dtype: object
The final accuracy after appending all the predicted values in a series is :  81.37342219219312 %

Using Stratified k-fold (with shuffle) (Using append predictions to series approach)

In [24]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = dfobj.iloc[:,0:7]
y = dfobj.iloc[:,[-1]]
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=5)
skf.get_n_splits(X, y)

print(skf)

StratifiedKFold(n_splits=5, random_state=5, shuffle=True)

In [25]:
pred_series=pd.Series()
for train_index, test_index in skf.split(X,y):
    print("TRAIN:", train_index, "TEST:", test_index)
    
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    X1_train, X1_test = X1.iloc[train_index], X1.iloc[test_index]
    y1_train, y1_test = y1.iloc[train_index], y1.iloc[test_index]
    
    X2_train, X2_test = X2.iloc[train_index], X2.iloc[test_index]
    y2_train, y2_test = y2.iloc[train_index], y2.iloc[test_index]
    
    pred_series=pred_series.append(predictall(X_test, X1_test, X2_test,  getcondProbs_obj(X_train,y_train,'income'),  getClassPriors(y_train['income'])))
    #we need to append and store the updated series in original pred_series, otherwise printing it would return an empty series
    

print(pred_series)

accuracy=(sum([a==b for (a,b) in zip(pred_series,df.iloc[pred_series.index,-1])])/len(pred_series))*100
print('The final accuracy after appending all the predicted values in a series is : ',accuracy,'%')

TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [    7     9    12 ... 32531 32535 32546]
TRAIN: [    1     2     3 ... 32558 32559 32560] TEST: [    0     5     6 ... 32544 32550 32557]
TRAIN: [    0     2     3 ... 32557 32558 32559] TEST: [    1    10    15 ... 32554 32556 32560]
TRAIN: [    0     1     3 ... 32556 32557 32560] TEST: [    2     4     8 ... 32555 32558 32559]
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [    3    11    16 ... 32545 32547 32553]
7         <=50K
9          >50K
12        <=50K
18        <=50K
22        <=50K
25        <=50K
29        <=50K
37        <=50K
39        <=50K
40        <=50K
41        <=50K
44        <=50K
51        <=50K
54        <=50K
63         >50K
66        <=50K
70        <=50K
73        <=50K
83        <=50K
92        <=50K
93         >50K
96         >50K
97        <=50K
110       <=50K
113        >50K
116       <=50K
124       <=50K
125       <=50K
126       <=50K
129       <=50K
          ...
32427     <=50K
32430     <=50K
32431     <=50K
32434      >50K
32443     <=50K
32448     <=50K
32449      >50K
32451     <=50K
32456     <=50K
32459     <=50K
32466      >50K
32467     <=50K
32471     <=50K
32472     <=50K
32474     <=50K
32481     <=50K
32482     <=50K
32484     <=50K
32486     <=50K
32488     <=50K
32496     <=50K
32506     <=50K
32507     <=50K
32510     <=50K
32513     <=50K
32516     <=50K
32528     <=50K
32545     <=50K
32547     <=50K
32553     <=50K
Length: 32561, dtype: object
The final accuracy after appending all the predicted values in a series is :  81.35499523970394 %